-- MySQL Script generated by MySQL Workbench
-- Thu Jul 25 15:23:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`buildings` (
  `building_no` CHAR(1) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `security_no` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`building_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`owners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`owners` (
  `owner_id` INT NOT NULL,
  `owner_name` VARCHAR(45) NOT NULL,
  `contact_no` VARCHAR(20) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`owner_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flats` (
  `apartment_id` INT(4) NOT NULL,
  `building_no` CHAR(1) NOT NULL,
  `owner_id` INT NOT NULL,
  `floor_no` INT(2) NOT NULL,
  `flat_no` INT(4) NOT NULL,
  `bathrooms` INT(1) NOT NULL,
  `bedrooms` INT(1) NOT NULL,
  `area` INT NOT NULL,
  `rent` INT NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `image_link` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`apartment_id`),
  INDEX `fk_flats_buildings_idx` (`building_no` ASC) VISIBLE,
  INDEX `fk_flats_1_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_flats_buildings`
    FOREIGN KEY (`building_no`)
    REFERENCES `mydb`.`buildings` (`building_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flats_1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`owners` (`owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tenants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tenants` (
  `tenant_id` INT NOT NULL,
  `tenant_name` VARCHAR(45) NOT NULL,
  `apartment_id` INT(4) NOT NULL,
  `contact_no` VARCHAR(20) NOT NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`tenant_id`),
  INDEX `fk_tenants_flats1_idx` (`apartment_id` ASC) VISIBLE,
  CONSTRAINT `fk_tenants_flats1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `mydb`.`flats` (`apartment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lease` (
  `lease_no` INT NOT NULL,
  `owner_id` INT NOT NULL,
  `tenant_id` INT NOT NULL,
  `apartment_id` INT(4) NOT NULL,
  `reg_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `tenure` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`lease_no`),
  INDEX `fk_lease_owners1_idx` (`owner_id` ASC) VISIBLE,
  INDEX `fk_lease_tenants1_idx` (`tenant_id` ASC) VISIBLE,
  INDEX `fk_lease_flats1_idx` (`apartment_id` ASC) VISIBLE,
  CONSTRAINT `fk_lease_owners1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`owners` (`owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lease_tenants1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `mydb`.`tenants` (`tenant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lease_flats1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `mydb`.`flats` (`apartment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `contact_no` VARCHAR(20) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visitation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visitation` (
  `visitation_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `apartment_id` INT(4) NOT NULL,
  `visit_date` DATE NOT NULL,
  `visit_time_slot` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`visitation_id`),
  INDEX `fk_visitation_flats1_idx` (`apartment_id` ASC) VISIBLE,
  INDEX `fk_visitation_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_visitation_flats1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `mydb`.`flats` (`apartment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visitation_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posts` (
  `post_id` INT NOT NULL,
  `apartment_id` INT(4) NOT NULL,
  `status` VARCHAR(8) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `image_link` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `fk_posts_flats1_idx` (`apartment_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_flats1`
    FOREIGN KEY (`apartment_id`)
    REFERENCES `mydb`.`flats` (`apartment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maintenance requests_owners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maintenance requests_owners` (
  `owner_request_id` INT NOT NULL,
  `owner_id` INT NOT NULL,
  `tenant_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1000) NULL,
  `raised_date` DATE NOT NULL,
  `complete_date` DATE NOT NULL,
  PRIMARY KEY (`owner_request_id`),
  INDEX `fk_maintenance requests_owners_owners1_idx` (`owner_id` ASC) VISIBLE,
  INDEX `fk_maintenance requests_owners_tenants1_idx` (`tenant_id` ASC) VISIBLE,
  CONSTRAINT `fk_maintenance requests_owners_owners1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `mydb`.`owners` (`owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maintenance requests_owners_tenants1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `mydb`.`tenants` (`tenant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
